// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package protobuf;

public final class Commands {
  private Commands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .protobuf.Command.Module module = 1;
    boolean hasModule();
    protobuf.Commands.Command.Module getModule();
    
    // optional .protobuf.Command.Action action = 2;
    boolean hasAction();
    protobuf.Commands.Command.Action getAction();
    
    // optional int32 interval = 3;
    boolean hasInterval();
    int getInterval();
    
    // optional int32 red = 4;
    boolean hasRed();
    int getRed();
    
    // optional int32 green = 5;
    boolean hasGreen();
    int getGreen();
    
    // optional int32 blue = 6;
    boolean hasBlue();
    int getBlue();
  }
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(Builder builder) {
      super(builder);
    }
    private Command(boolean noInit) {}
    
    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }
    
    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.Commands.internal_static_protobuf_Command_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.Commands.internal_static_protobuf_Command_fieldAccessorTable;
    }
    
    public enum Module
        implements com.google.protobuf.ProtocolMessageEnum {
      NONE(0, 1),
      CONSTANT(1, 2),
      CURSOR(2, 3),
      FADE(3, 4),
      RANDOM(4, 5),
      SCREEN(5, 6),
      ;
      
      public static final int NONE_VALUE = 1;
      public static final int CONSTANT_VALUE = 2;
      public static final int CURSOR_VALUE = 3;
      public static final int FADE_VALUE = 4;
      public static final int RANDOM_VALUE = 5;
      public static final int SCREEN_VALUE = 6;
      
      
      public final int getNumber() { return value; }
      
      public static Module valueOf(int value) {
        switch (value) {
          case 1: return NONE;
          case 2: return CONSTANT;
          case 3: return CURSOR;
          case 4: return FADE;
          case 5: return RANDOM;
          case 6: return SCREEN;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Module>() {
              public Module findValueByNumber(int number) {
                return Module.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.Commands.Command.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Module[] VALUES = {
        NONE, CONSTANT, CURSOR, FADE, RANDOM, SCREEN, 
      };
      
      public static Module valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Module(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:protobuf.Command.Module)
    }
    
    public enum Action
        implements com.google.protobuf.ProtocolMessageEnum {
      START(0, 1),
      STOP(1, 2),
      PAUSE(2, 3),
      RESUME(3, 4),
      ;
      
      public static final int START_VALUE = 1;
      public static final int STOP_VALUE = 2;
      public static final int PAUSE_VALUE = 3;
      public static final int RESUME_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static Action valueOf(int value) {
        switch (value) {
          case 1: return START;
          case 2: return STOP;
          case 3: return PAUSE;
          case 4: return RESUME;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Action>() {
              public Action findValueByNumber(int number) {
                return Action.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.Commands.Command.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final Action[] VALUES = {
        START, STOP, PAUSE, RESUME, 
      };
      
      public static Action valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Action(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:protobuf.Command.Action)
    }
    
    private int bitField0_;
    // optional .protobuf.Command.Module module = 1;
    public static final int MODULE_FIELD_NUMBER = 1;
    private protobuf.Commands.Command.Module module_;
    public boolean hasModule() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public protobuf.Commands.Command.Module getModule() {
      return module_;
    }
    
    // optional .protobuf.Command.Action action = 2;
    public static final int ACTION_FIELD_NUMBER = 2;
    private protobuf.Commands.Command.Action action_;
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public protobuf.Commands.Command.Action getAction() {
      return action_;
    }
    
    // optional int32 interval = 3;
    public static final int INTERVAL_FIELD_NUMBER = 3;
    private int interval_;
    public boolean hasInterval() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getInterval() {
      return interval_;
    }
    
    // optional int32 red = 4;
    public static final int RED_FIELD_NUMBER = 4;
    private int red_;
    public boolean hasRed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getRed() {
      return red_;
    }
    
    // optional int32 green = 5;
    public static final int GREEN_FIELD_NUMBER = 5;
    private int green_;
    public boolean hasGreen() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getGreen() {
      return green_;
    }
    
    // optional int32 blue = 6;
    public static final int BLUE_FIELD_NUMBER = 6;
    private int blue_;
    public boolean hasBlue() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public int getBlue() {
      return blue_;
    }
    
    private void initFields() {
      module_ = protobuf.Commands.Command.Module.NONE;
      action_ = protobuf.Commands.Command.Action.START;
      interval_ = 0;
      red_ = 0;
      green_ = 0;
      blue_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, module_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, action_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, interval_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, red_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, green_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, blue_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, module_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, interval_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, red_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, green_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, blue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static protobuf.Commands.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.Commands.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.Commands.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static protobuf.Commands.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.Commands.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.Commands.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static protobuf.Commands.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.Commands.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static protobuf.Commands.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static protobuf.Commands.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(protobuf.Commands.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements protobuf.Commands.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.Commands.internal_static_protobuf_Command_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.Commands.internal_static_protobuf_Command_fieldAccessorTable;
      }
      
      // Construct using protobuf.Commands.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        module_ = protobuf.Commands.Command.Module.NONE;
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = protobuf.Commands.Command.Action.START;
        bitField0_ = (bitField0_ & ~0x00000002);
        interval_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        red_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        green_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        blue_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.Commands.Command.getDescriptor();
      }
      
      public protobuf.Commands.Command getDefaultInstanceForType() {
        return protobuf.Commands.Command.getDefaultInstance();
      }
      
      public protobuf.Commands.Command build() {
        protobuf.Commands.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private protobuf.Commands.Command buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        protobuf.Commands.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public protobuf.Commands.Command buildPartial() {
        protobuf.Commands.Command result = new protobuf.Commands.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.module_ = module_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.interval_ = interval_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.red_ = red_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.green_ = green_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.blue_ = blue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.Commands.Command) {
          return mergeFrom((protobuf.Commands.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(protobuf.Commands.Command other) {
        if (other == protobuf.Commands.Command.getDefaultInstance()) return this;
        if (other.hasModule()) {
          setModule(other.getModule());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasInterval()) {
          setInterval(other.getInterval());
        }
        if (other.hasRed()) {
          setRed(other.getRed());
        }
        if (other.hasGreen()) {
          setGreen(other.getGreen());
        }
        if (other.hasBlue()) {
          setBlue(other.getBlue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              protobuf.Commands.Command.Module value = protobuf.Commands.Command.Module.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                module_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              protobuf.Commands.Command.Action value = protobuf.Commands.Command.Action.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                action_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              interval_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              red_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              green_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              blue_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .protobuf.Command.Module module = 1;
      private protobuf.Commands.Command.Module module_ = protobuf.Commands.Command.Module.NONE;
      public boolean hasModule() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public protobuf.Commands.Command.Module getModule() {
        return module_;
      }
      public Builder setModule(protobuf.Commands.Command.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        module_ = value;
        onChanged();
        return this;
      }
      public Builder clearModule() {
        bitField0_ = (bitField0_ & ~0x00000001);
        module_ = protobuf.Commands.Command.Module.NONE;
        onChanged();
        return this;
      }
      
      // optional .protobuf.Command.Action action = 2;
      private protobuf.Commands.Command.Action action_ = protobuf.Commands.Command.Action.START;
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public protobuf.Commands.Command.Action getAction() {
        return action_;
      }
      public Builder setAction(protobuf.Commands.Command.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = protobuf.Commands.Command.Action.START;
        onChanged();
        return this;
      }
      
      // optional int32 interval = 3;
      private int interval_ ;
      public boolean hasInterval() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getInterval() {
        return interval_;
      }
      public Builder setInterval(int value) {
        bitField0_ |= 0x00000004;
        interval_ = value;
        onChanged();
        return this;
      }
      public Builder clearInterval() {
        bitField0_ = (bitField0_ & ~0x00000004);
        interval_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 red = 4;
      private int red_ ;
      public boolean hasRed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getRed() {
        return red_;
      }
      public Builder setRed(int value) {
        bitField0_ |= 0x00000008;
        red_ = value;
        onChanged();
        return this;
      }
      public Builder clearRed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        red_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 green = 5;
      private int green_ ;
      public boolean hasGreen() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getGreen() {
        return green_;
      }
      public Builder setGreen(int value) {
        bitField0_ |= 0x00000010;
        green_ = value;
        onChanged();
        return this;
      }
      public Builder clearGreen() {
        bitField0_ = (bitField0_ & ~0x00000010);
        green_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 blue = 6;
      private int blue_ ;
      public boolean hasBlue() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getBlue() {
        return blue_;
      }
      public Builder setBlue(int value) {
        bitField0_ |= 0x00000020;
        blue_ = value;
        onChanged();
        return this;
      }
      public Builder clearBlue() {
        bitField0_ = (bitField0_ & ~0x00000020);
        blue_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.Command)
    }
    
    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.Command)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Command_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016commands.proto\022\010protobuf\"\237\002\n\007Command\022(" +
      "\n\006module\030\001 \001(\0162\030.protobuf.Command.Module" +
      "\022(\n\006action\030\002 \001(\0162\030.protobuf.Command.Acti" +
      "on\022\020\n\010interval\030\003 \001(\005\022\013\n\003red\030\004 \001(\005\022\r\n\005gre" +
      "en\030\005 \001(\005\022\014\n\004blue\030\006 \001(\005\"N\n\006Module\022\010\n\004NONE" +
      "\020\001\022\014\n\010CONSTANT\020\002\022\n\n\006CURSOR\020\003\022\010\n\004FADE\020\004\022\n" +
      "\n\006RANDOM\020\005\022\n\n\006SCREEN\020\006\"4\n\006Action\022\t\n\005STAR" +
      "T\020\001\022\010\n\004STOP\020\002\022\t\n\005PAUSE\020\003\022\n\n\006RESUME\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_protobuf_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_protobuf_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_protobuf_Command_descriptor,
              new java.lang.String[] { "Module", "Action", "Interval", "Red", "Green", "Blue", },
              protobuf.Commands.Command.class,
              protobuf.Commands.Command.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
