// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commands.proto

package clientcommands;

public final class Commands {
  private Commands() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .clientcommands.Command.Module module = 1;
    boolean hasModule();
    clientcommands.Commands.Command.Module getModule();
    
    // optional .clientcommands.Command.Action action = 2;
    boolean hasAction();
    clientcommands.Commands.Command.Action getAction();
  }
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(Builder builder) {
      super(builder);
    }
    private Command(boolean noInit) {}
    
    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }
    
    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return clientcommands.Commands.internal_static_clientcommands_Command_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return clientcommands.Commands.internal_static_clientcommands_Command_fieldAccessorTable;
    }
    
    public enum Module
        implements com.google.protobuf.ProtocolMessageEnum {
      NONE(0, 1),
      CONSTANT(1, 2),
      CURSOR(2, 3),
      FADE(3, 4),
      RANDOM(4, 5),
      SCREEN(5, 6),
      ;
      
      public static final int NONE_VALUE = 1;
      public static final int CONSTANT_VALUE = 2;
      public static final int CURSOR_VALUE = 3;
      public static final int FADE_VALUE = 4;
      public static final int RANDOM_VALUE = 5;
      public static final int SCREEN_VALUE = 6;
      
      
      public final int getNumber() { return value; }
      
      public static Module valueOf(int value) {
        switch (value) {
          case 1: return NONE;
          case 2: return CONSTANT;
          case 3: return CURSOR;
          case 4: return FADE;
          case 5: return RANDOM;
          case 6: return SCREEN;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Module>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Module>() {
              public Module findValueByNumber(int number) {
                return Module.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return clientcommands.Commands.Command.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Module[] VALUES = {
        NONE, CONSTANT, CURSOR, FADE, RANDOM, SCREEN, 
      };
      
      public static Module valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Module(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:clientcommands.Command.Module)
    }
    
    public enum Action
        implements com.google.protobuf.ProtocolMessageEnum {
      START(0, 1),
      STOP(1, 2),
      PAUSE(2, 3),
      RESUME(3, 4),
      ;
      
      public static final int START_VALUE = 1;
      public static final int STOP_VALUE = 2;
      public static final int PAUSE_VALUE = 3;
      public static final int RESUME_VALUE = 4;
      
      
      public final int getNumber() { return value; }
      
      public static Action valueOf(int value) {
        switch (value) {
          case 1: return START;
          case 2: return STOP;
          case 3: return PAUSE;
          case 4: return RESUME;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Action>() {
              public Action findValueByNumber(int number) {
                return Action.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return clientcommands.Commands.Command.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final Action[] VALUES = {
        START, STOP, PAUSE, RESUME, 
      };
      
      public static Action valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Action(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:clientcommands.Command.Action)
    }
    
    private int bitField0_;
    // optional .clientcommands.Command.Module module = 1;
    public static final int MODULE_FIELD_NUMBER = 1;
    private clientcommands.Commands.Command.Module module_;
    public boolean hasModule() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public clientcommands.Commands.Command.Module getModule() {
      return module_;
    }
    
    // optional .clientcommands.Command.Action action = 2;
    public static final int ACTION_FIELD_NUMBER = 2;
    private clientcommands.Commands.Command.Action action_;
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public clientcommands.Commands.Command.Action getAction() {
      return action_;
    }
    
    private void initFields() {
      module_ = clientcommands.Commands.Command.Module.NONE;
      action_ = clientcommands.Commands.Command.Action.START;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, module_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, action_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, module_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static clientcommands.Commands.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static clientcommands.Commands.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static clientcommands.Commands.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static clientcommands.Commands.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static clientcommands.Commands.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static clientcommands.Commands.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static clientcommands.Commands.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static clientcommands.Commands.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static clientcommands.Commands.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static clientcommands.Commands.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(clientcommands.Commands.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements clientcommands.Commands.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return clientcommands.Commands.internal_static_clientcommands_Command_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return clientcommands.Commands.internal_static_clientcommands_Command_fieldAccessorTable;
      }
      
      // Construct using clientcommands.Commands.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        module_ = clientcommands.Commands.Command.Module.NONE;
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = clientcommands.Commands.Command.Action.START;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return clientcommands.Commands.Command.getDescriptor();
      }
      
      public clientcommands.Commands.Command getDefaultInstanceForType() {
        return clientcommands.Commands.Command.getDefaultInstance();
      }
      
      public clientcommands.Commands.Command build() {
        clientcommands.Commands.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private clientcommands.Commands.Command buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        clientcommands.Commands.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public clientcommands.Commands.Command buildPartial() {
        clientcommands.Commands.Command result = new clientcommands.Commands.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.module_ = module_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof clientcommands.Commands.Command) {
          return mergeFrom((clientcommands.Commands.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(clientcommands.Commands.Command other) {
        if (other == clientcommands.Commands.Command.getDefaultInstance()) return this;
        if (other.hasModule()) {
          setModule(other.getModule());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              clientcommands.Commands.Command.Module value = clientcommands.Commands.Command.Module.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                module_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              clientcommands.Commands.Command.Action value = clientcommands.Commands.Command.Action.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                action_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .clientcommands.Command.Module module = 1;
      private clientcommands.Commands.Command.Module module_ = clientcommands.Commands.Command.Module.NONE;
      public boolean hasModule() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public clientcommands.Commands.Command.Module getModule() {
        return module_;
      }
      public Builder setModule(clientcommands.Commands.Command.Module value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        module_ = value;
        onChanged();
        return this;
      }
      public Builder clearModule() {
        bitField0_ = (bitField0_ & ~0x00000001);
        module_ = clientcommands.Commands.Command.Module.NONE;
        onChanged();
        return this;
      }
      
      // optional .clientcommands.Command.Action action = 2;
      private clientcommands.Commands.Command.Action action_ = clientcommands.Commands.Command.Action.START;
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public clientcommands.Commands.Command.Action getAction() {
        return action_;
      }
      public Builder setAction(clientcommands.Commands.Command.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        action_ = value;
        onChanged();
        return this;
      }
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = clientcommands.Commands.Command.Action.START;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:clientcommands.Command)
    }
    
    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:clientcommands.Command)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_clientcommands_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_clientcommands_Command_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016commands.proto\022\016clientcommands\"\357\001\n\007Com" +
      "mand\022.\n\006module\030\001 \001(\0162\036.clientcommands.Co" +
      "mmand.Module\022.\n\006action\030\002 \001(\0162\036.clientcom" +
      "mands.Command.Action\"N\n\006Module\022\010\n\004NONE\020\001" +
      "\022\014\n\010CONSTANT\020\002\022\n\n\006CURSOR\020\003\022\010\n\004FADE\020\004\022\n\n\006" +
      "RANDOM\020\005\022\n\n\006SCREEN\020\006\"4\n\006Action\022\t\n\005START\020" +
      "\001\022\010\n\004STOP\020\002\022\t\n\005PAUSE\020\003\022\n\n\006RESUME\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_clientcommands_Command_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_clientcommands_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_clientcommands_Command_descriptor,
              new java.lang.String[] { "Module", "Action", },
              clientcommands.Commands.Command.class,
              clientcommands.Commands.Command.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
